name: my-package
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - build
  - black
  - isort
  - flake8
  - flake8-bugbear
  - flake8-comprehensions
  - pep8-naming
  - pytest
  - coverage
  - pip:
    - tensorflow>=2.10,<3
